### ISSUE TITLE
conflict when include_song == False

### ISSUE THREAD

**Issue by adpala** [janclemenslab/xarray-behave#68]
When trying to run:
```
import numpy as np
import xarray_behave as xb
root_path = f"Z:/#Common/backlight"
datename = 'localhost-20200220_093717'
try:
    dataset = xb.assemble(datename, root=root_path, target_sampling_rate=100,
                          resample_video_data=True, include_song=False)
except:
    dataset = xb.assemble(datename, root=root_path, dat_path='dat.processed', target_sampling_rate=100,
                          resample_video_data=True, include_song=False)
```

Error returned:
```
Traceback (most recent call last):
  File "inspecting_sampling_frequency.py", line 33, in <module>
    resample_video_data=True, include_song=False)
  File "z:\apalaci\code\src\tools\xarray-behave\src\xarray_behave\xarray_behave.py", line 175, in assemble
    event_seconds = auto_event_seconds.copy()
UnboundLocalError: local variable 'auto_event_seconds' referenced before assignment
```

Points to xarray_behave.py line 175 - 181:
```
    event_seconds = auto_event_seconds.copy()
    event_seconds.update(manual_event_seconds)
    event_categories = auto_event_categories.copy()
    event_categories.update(manual_event_categories)
    event_seconds = ld.fix_keys(event_seconds)
    event_categories = ld.fix_keys(event_categories)
```
but auto_event_seconds only exists if `include_song == True` at lines 110-135, so there it crashed.

Probably some `if` conditions for the case of `include_song == False` are required to give default variables.

**Comment by adpala** [comment]
Allowing `include_song == True` works, but probably should not be required for experimental setups without song recording.
