### ISSUE TITLE
version conflicts during installation of xarray-behave[gui]

### ISSUE THREAD

**Issue by adpala** [janclemenslab/xarray-behave#69]
Following installation instructions for xarray-behave[gui] on a new environment, the following errors are prompted:
```
ERROR: xarray 0.15.1 has requirement numpy>=1.15, but you'll have numpy 1.14.5 which is incompatible.
ERROR: tifffile 2020.5.25 has requirement numpy>=1.15.1, but you'll have numpy 1.14.5 which is incompatible.
ERROR: scikit-image 0.17.2 has requirement numpy>=1.15.1, but you'll have numpy 1.14.5 which is incompatible.
```

Is there a way can avoid these?
As a result my numpy is conflicting whenever I try using `xb`, even at `xb --help`, showing:

```
Traceback (most recent call last):
  File "c:\users\apalaci\appdata\local\continuum\miniconda3\envs\xb_gui\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\apalaci\appdata\local\continuum\miniconda3\envs\xb_gui\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\apalaci\AppData\Local\Continuum\miniconda3\envs\xb_gui\Scripts\xb.exe\__main__.py", line 4, in <module>
  File "c:\users\apalaci\appdata\local\continuum\miniconda3\envs\xb_gui\lib\site-packages\xarray_behave\__init__.py", line 4, in <module>
    from .xarray_behave import assemble, assemble_metrics, load, save, from_wav
  File "c:\users\apalaci\appdata\local\continuum\miniconda3\envs\xb_gui\lib\site-packages\xarray_behave\xarray_behave.py", line 10, in <module>
    from . import loaders as ld
  File "c:\users\apalaci\appdata\local\continuum\miniconda3\envs\xb_gui\lib\site-packages\xarray_behave\loaders.py", line 4, in <module>
    import flammkuchen as dd_io
  File "c:\users\apalaci\appdata\local\continuum\miniconda3\envs\xb_gui\lib\site-packages\flammkuchen\__init__.py", line 4, in <module>
    import tables
  File "c:\users\apalaci\appdata\local\continuum\miniconda3\envs\xb_gui\lib\site-packages\tables\__init__.py", line 99, in <module>
    from .utilsextension import (
  File "__init__.pxd", line 918, in init tables.utilsextension
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

**Comment by postpop** [comment]
Didn't happen for me when I followed the instructions on a windows machine. Afshin had recently installed it and he did not have that issue. So the error seems system-specific.

- Can you post all output produced during all steps of the installation? That may have some information I can use to help.
- Do you have the latest conda version?
- When is numpy 1.14.5 being installed? For me, numpy 1.18.4 is installed during `conda install pyside2 pyqtgraph python-sounddevice -c conda-forge -y`. Does that happen for you as well and it is then overwritten by an older version during `conda install pyside2 pyqtgraph python-sounddevice -c conda-forge -y`?
- Can you manually update numpy to solve the problem?

**Comment by adpala** [comment]
from `conda create -n xb_gui python=3.7 -y`:
```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\apalaci\AppData\Local\Continuum\miniconda3\envs\xb_gui

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-20.1.1                 |             py_1         1.1 MB  conda-forge
    setuptools-46.4.0          |   py37hc8dfbb8_0         658 KB  conda-forge
    vc-14.1                    |       h869be7e_1           6 KB  conda-forge
    vs2015_runtime-14.16.27012 |       h30e32a0_2         2.2 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.9 MB

The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/win-64::ca-certificates-2020.4.5.1-hecc5488_0
  certifi            conda-forge/win-64::certifi-2020.4.5.1-py37hc8dfbb8_0
  openssl            conda-forge/win-64::openssl-1.1.1g-he774522_0
  pip                conda-forge/noarch::pip-20.1.1-py_1
  python             conda-forge/win-64::python-3.7.6-h60c2a47_5_cpython
  python_abi         conda-forge/win-64::python_abi-3.7-1_cp37m
  setuptools         conda-forge/win-64::setuptools-46.4.0-py37hc8dfbb8_0
  sqlite             conda-forge/win-64::sqlite-3.30.1-hfa6e2cd_0
  vc                 conda-forge/win-64::vc-14.1-h869be7e_1
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.16.27012-h30e32a0_2
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  wincertstore       conda-forge/win-64::wincertstore-0.2-py37_1003



Downloading and Extracting Packages
vs2015_runtime-14.16 | 2.2 MB    | ############################################################################ | 100%
vc-14.1              | 6 KB      | ############################################################################ | 100%
pip-20.1.1           | 1.1 MB    | ############################################################################ | 100%
setuptools-46.4.0    | 658 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate xb_gui
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```
from `conda activate xb_gui` and `conda install pyside2 pyqtgraph python-sounddevice -c conda-forge -y`
```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\apalaci\AppData\Local\Continuum\miniconda3\envs\xb_gui

  added / updated specs:
    - pyqtgraph
    - pyside2
    - python-sounddevice


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libxml2-2.9.10             |       h5d81f1c_1         3.4 MB  conda-forge
    libxslt-1.1.33             |       h579f668_1         499 KB  conda-forge
    numpy-1.18.4               |   py37hae9e721_0         4.8 MB  conda-forge
    portaudio-19.6.0           |       h6538335_2           5 KB  conda-forge
    pyqt-5.12.3                |   py37h1834ac0_3         4.8 MB  conda-forge
    pyside2-5.13.2             |   py37hfa7ce6d_2        10.9 MB  conda-forge
    python-sounddevice-0.3.15  |     pyh8c360ce_0          29 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        24.5 MB

The following NEW packages will be INSTALLED:

  cffi               conda-forge/win-64::cffi-1.14.0-py37ha419a9e_0
  icu                conda-forge/win-64::icu-64.2-he025d50_1
  intel-openmp       pkgs/main/win-64::intel-openmp-2020.0-166
  jpeg               conda-forge/win-64::jpeg-9c-hfa6e2cd_1001
  libblas            conda-forge/win-64::libblas-3.8.0-15_mkl
  libcblas           conda-forge/win-64::libcblas-3.8.0-15_mkl
  libclang           conda-forge/win-64::libclang-9.0.1-default_hf44288c_0
  libiconv           conda-forge/win-64::libiconv-1.15-hfa6e2cd_1006
  liblapack          conda-forge/win-64::liblapack-3.8.0-15_mkl
  libpng             conda-forge/win-64::libpng-1.6.37-hfe6a214_1
  libxml2            conda-forge/win-64::libxml2-2.9.10-h5d81f1c_1
  libxslt            conda-forge/win-64::libxslt-1.1.33-h579f668_1
  mkl                pkgs/main/win-64::mkl-2020.0-166
  numpy              conda-forge/win-64::numpy-1.18.4-py37hae9e721_0
  portaudio          conda-forge/win-64::portaudio-19.6.0-h6538335_2
  pycparser          conda-forge/noarch::pycparser-2.20-py_0
  pyqt               conda-forge/win-64::pyqt-5.12.3-py37h1834ac0_3
  pyqtgraph          conda-forge/noarch::pyqtgraph-0.11.0rc0-py_0
  pyside2            conda-forge/win-64::pyside2-5.13.2-py37hfa7ce6d_2
  python-sounddevice conda-forge/noarch::python-sounddevice-0.3.15-pyh8c360ce_0
  qt                 conda-forge/win-64::qt-5.12.5-h7ef1ec2_0
  zlib               conda-forge/win-64::zlib-1.2.11-h2fa13f4_1006



Downloading and Extracting Packages
libxslt-1.1.33       | 499 KB    | ############################################################################ | 100%
python-sounddevice-0 | 29 KB     | ############################################################################ | 100%
libxml2-2.9.10       | 3.4 MB    | ############################################################################ | 100%
pyside2-5.13.2       | 10.9 MB   | ############################################################################ | 100%
pyqt-5.12.3          | 4.8 MB    | ############################################################################ | 100%
portaudio-19.6.0     | 5 KB      | ############################################################################ | 100%
numpy-1.18.4         | 4.8 MB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

Here I had to fix pip, as it was not finding a module, which I did doing `python -m pip install --user --upgrade pip`:
```
Collecting pip
  Downloading https://files.pythonhosted.org/packages/43/84/23ed6a1796480a6f1a2d38f2802901d078266bda38388954d01d3f2e821d/pip-20.1.1-py2.py3-none-any.whl (1.5MB)
     |████████████████████████████████| 1.5MB 3.2MB/s
Installing collected packages: pip
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
  WARNING: The scripts pip.exe, pip3.7.exe and pip3.exe are installed in 'C:\Users\apalaci\AppData\Roaming\Python\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-20.1.1
```

then `pip install xarray-behave[gui]`
```
Collecting xarray-behave[gui]
  Downloading xarray_behave-0.7.3-py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 5.1 MB/s
Requirement already satisfied: numpy in c:\users\apalaci\appdata\roaming\python\python37\site-packages (from xarray-behave[gui]) (1.14.5)
Collecting xarray
  Using cached xarray-0.15.1-py3-none-any.whl (668 kB)
Collecting scipy
  Downloading scipy-1.4.1-cp37-cp37m-win_amd64.whl (30.9 MB)
     |████████████████████████████████| 30.9 MB 6.4 MB/s
Collecting soundfile
  Using cached SoundFile-0.10.3.post1-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33-none-win_amd64.whl (689 kB)
Collecting dask
  Downloading dask-2.17.0-py3-none-any.whl (812 kB)
     |████████████████████████████████| 812 kB ...
Collecting samplestamps
  Using cached samplestamps-0.2.3-py3-none-any.whl (8.3 kB)
Collecting toolz
  Using cached toolz-0.10.0.tar.gz (49 kB)
Collecting flammkuchen
  Using cached flammkuchen-0.9.2-py2.py3-none-any.whl (16 kB)
Processing c:\users\apalaci\appdata\local\pip\cache\wheels\e1\5b\25\24c685604b91139aba00a5b6299b53e7a0661f737f27782559\zarr-2.4.0-cp37-none-any.whl
Collecting h5py
  Using cached h5py-2.10.0-cp37-cp37m-win_amd64.whl (2.5 MB)
Collecting pyside2; extra == "gui"
  Downloading PySide2-5.15.0-5.15.0-cp35.cp36.cp37.cp38-none-win_amd64.whl (139.6 MB)
     |████████████████████████████████| 139.6 MB 33 kB/s
Requirement already satisfied: pyqtgraph; extra == "gui" in c:\users\apalaci\appdata\local\continuum\miniconda3\envs\xb_gui\lib\site-packages (from xarray-behave[gui]) (0.11.0rc0)
Collecting scikit-image; extra == "gui"
  Downloading scikit_image-0.17.2-cp37-cp37m-win_amd64.whl (11.5 MB)
     |████████████████████████████████| 11.5 MB ...
Collecting opencv-python; extra == "gui"
  Downloading opencv_python-4.2.0.34-cp37-cp37m-win_amd64.whl (33.0 MB)
     |████████████████████████████████| 33.0 MB 6.4 MB/s
Collecting pyyaml; extra == "gui"
  Downloading PyYAML-5.3.1-cp37-cp37m-win_amd64.whl (216 kB)
     |████████████████████████████████| 216 kB ...
Collecting pyvideoreader; extra == "gui"
  Downloading pyvideoreader-0.4.3-py3-none-any.whl (16 kB)
Collecting defopt; extra == "gui"
  Downloading defopt-6.0.tar.gz (33 kB)
Requirement already satisfied: sounddevice; extra == "gui" in c:\users\apalaci\appdata\local\continuum\miniconda3\envs\xb_gui\lib\site-packages (from xarray-behave[gui]) (0.3.15)
Requirement already satisfied: setuptools>=41.2 in c:\users\apalaci\appdata\local\continuum\miniconda3\envs\xb_gui\lib\site-packages (from xarray->xarray-behave[gui]) (46.4.0.post20200518)
Collecting pandas>=0.25
  Downloading pandas-1.0.3-cp37-cp37m-win_amd64.whl (8.7 MB)
     |████████████████████████████████| 8.7 MB 6.4 MB/s
Requirement already satisfied: cffi>=1.0 in c:\users\apalaci\appdata\local\continuum\miniconda3\envs\xb_gui\lib\site-packages (from soundfile->xarray-behave[gui]) (1.14.0)
Collecting tables
  Using cached tables-3.6.1-2-cp37-cp37m-win_amd64.whl (3.1 MB)
Processing c:\users\apalaci\appdata\local\pip\cache\wheels\1d\d9\58\9808b306744df0208fccc640d3d9952a5bc7468502d42897d5\asciitree-0.3.3-cp37-none-any.whl
Processing c:\users\apalaci\appdata\local\pip\cache\wheels\ca\07\ed\fea2e120cbb91d90b577c5ac56b4b082024f56fcd88e9afa55\numcodecs-0.6.4-cp37-cp37m-win_amd64.whl
Collecting fasteners
  Using cached fasteners-0.15-py2.py3-none-any.whl (23 kB)
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting shiboken2==5.15.0
  Downloading shiboken2-5.15.0-5.15.0-cp35.cp36.cp37.cp38-none-win_amd64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB ...
Collecting pillow!=7.1.0,!=7.1.1,>=4.3.0
  Downloading Pillow-7.1.2-cp37-cp37m-win_amd64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 6.8 MB/s
Collecting networkx>=2.0
  Using cached networkx-2.4-py3-none-any.whl (1.6 MB)
Collecting PyWavelets>=1.1.1
  Using cached PyWavelets-1.1.1-cp37-cp37m-win_amd64.whl (4.2 MB)
Collecting matplotlib!=3.0.0,>=2.0.0
  Downloading matplotlib-3.2.1-cp37-cp37m-win_amd64.whl (9.2 MB)
     |████████████████████████████████| 9.2 MB 6.4 MB/s
Collecting tifffile>=2019.7.26
  Downloading tifffile-2020.5.25-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB ...
Collecting imageio>=2.3.0
  Downloading imageio-2.8.0-py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB ...
Collecting docutils>=0.10
  Using cached docutils-0.16-py2.py3-none-any.whl (548 kB)
Collecting sphinxcontrib-napoleon>=0.7.0
  Using cached sphinxcontrib_napoleon-0.7-py2.py3-none-any.whl (17 kB)
Collecting typing_extensions>=3.7.4
  Using cached typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
Collecting typing_inspect>=0.3.1
  Using cached typing_inspect-0.6.0-py3-none-any.whl (8.1 kB)
Collecting colorama>=0.3.4
  Downloading colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting pytz>=2017.2
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 6.8 MB/s
Collecting python-dateutil>=2.6.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Requirement already satisfied: pycparser in c:\users\apalaci\appdata\local\continuum\miniconda3\envs\xb_gui\lib\site-packages (from cffi>=1.0->soundfile->xarray-behave[gui]) (2.20)
Collecting numexpr>=2.6.2
  Using cached numexpr-2.7.1-cp37-none-win_amd64.whl (90 kB)
Collecting monotonic>=0.1
  Using cached monotonic-1.5-py2.py3-none-any.whl (5.3 kB)
Collecting decorator>=4.3.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB ...
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.2.0-cp37-none-win_amd64.whl (57 kB)
     |████████████████████████████████| 57 kB ...
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting pockets>=0.3
  Using cached pockets-0.9.1-py2.py3-none-any.whl (26 kB)
Collecting mypy-extensions>=0.3.0
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Building wheels for collected packages: toolz, defopt
  Building wheel for toolz (setup.py) ... done
  Created wheel for toolz: filename=toolz-0.10.0-py3-none-any.whl size=55579 sha256=b8ae13b30b1d2765c90258b0df88c579c1a12152070fb9765c2ca0c4b81b2a3e
  Stored in directory: c:\users\apalaci\appdata\local\pip\cache\wheels\e2\83\7c\248063997a4f9ff6bf145822e620e8c37117a6b4c765584077
  Building wheel for defopt (setup.py) ... done
  Created wheel for defopt: filename=defopt-6.0-py3-none-any.whl size=13564 sha256=38fe8c6e9f7cd30cdb2e2f799124de32a806844a72223f1e400bc462120239ce
  Stored in directory: c:\users\apalaci\appdata\local\pip\cache\wheels\69\d5\2d\866015f819b726f2c658802239ad063f4d715cfe26e9d172e7
Successfully built toolz defopt
ERROR: xarray 0.15.1 has requirement numpy>=1.15, but you'll have numpy 1.14.5 which is incompatible.
ERROR: tifffile 2020.5.25 has requirement numpy>=1.15.1, but you'll have numpy 1.14.5 which is incompatible.
ERROR: scikit-image 0.17.2 has requirement numpy>=1.15.1, but you'll have numpy 1.14.5 which is incompatible.
Installing collected packages: pytz, six, python-dateutil, pandas, xarray, scipy, soundfile, dask, samplestamps, toolz, numexpr, tables, flammkuchen, asciitree, numcodecs, monotonic, fasteners, zarr, h5py, shiboken2, pyside2, pillow, decorator, networkx, PyWavelets, pyparsing, kiwisolver, cycler, matplotlib, tifffile, imageio, scikit-image, opencv-python, pyyaml, pyvideoreader, docutils, pockets, sphinxcontrib-napoleon, typing-extensions, mypy-extensions, typing-inspect, colorama, defopt, xarray-behave
Successfully installed PyWavelets-1.1.1 asciitree-0.3.3 colorama-0.4.3 cycler-0.10.0 dask-2.17.0 decorator-4.4.2 defopt-6.0 docutils-0.16 fasteners-0.15 flammkuchen-0.9.2 h5py-2.10.0 imageio-2.8.0 kiwisolver-1.2.0 matplotlib-3.2.1 monotonic-1.5 mypy-extensions-0.4.3 networkx-2.4 numcodecs-0.6.4 numexpr-2.7.1 opencv-python-4.2.0.34 pandas-1.0.3 pillow-7.1.2 pockets-0.9.1 pyparsing-2.4.7 pyside2-5.15.0 python-dateutil-2.8.1 pytz-2020.1 pyvideoreader-0.4.3 pyyaml-5.3.1 samplestamps-0.2.3 scikit-image-0.17.2 scipy-1.4.1 shiboken2-5.15.0 six-1.15.0 soundfile-0.10.3.post1 sphinxcontrib-napoleon-0.7 tables-3.6.1 tifffile-2020.5.25 toolz-0.10.0 typing-extensions-3.7.4.2 typing-inspect-0.6.0 xarray-0.15.1 xarray-behave-0.7.3 zarr-2.4.0
```


`numpy `doesn't let me update as it actually has still the `1.18.4` version. For some reason it was not recognized properly during the error prints. And somehow it still conflicts with the `xb`.

My conda version is 4.8.3 as well.

I do notice in the line where numpy is recognized, before xarray is installed, that the path it shows is not to the numpy in my `xb-gui` environment:
```
Collecting xarray-behave[gui]
  Downloading xarray_behave-0.7.3-py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 5.1 MB/s
Requirement already satisfied: numpy in c:\users\apalaci\appdata\roaming\python\python37\site-packages (from xarray-behave[gui]) (1.14.5)
```

**Comment by postpop** [comment]
The fact that you had to update pip in one of the steps means that `pip` is not referring to the pip from then env - the latest version of pip gets installed into the new env during env creation:
`pip                conda-forge/noarch::pip-20.1.1-py_1`

`pip --version` will print the path to the python executable associated with pip. On the windows machine I used for testing, it returned (after activating the env):
`pip 20.0.2 from C:\Miniconda3\envs\xb_gui\lib\site-packages\pip (python 3.7)` 

My guess is that for you this will refer to pip in the base env.

`python -m pip install xarray-behave[gui]` will use the pip associated with the env's python executable. If this solves it then please update the instructions accordingly. 

Python package management is unnecessarily messy - I had initially used a conda env yml file but that caused the same amount of problems since it pre-scribed a specific combination of package versions that only worked on some architectures.

**Comment by adpala** [comment]
The source of the problem is correct, pip is still not the correct one, but `python -m pip`  still refers to the same pip which is not in my environment:
```
pip 20.1.1 from C:\Users\apalaci\AppData\Roaming\Python\Python37\site-packages\pip (python 3.7)
```
This is not even my base environment. My miniconda is in: 
```
C:\Users\apalaci\AppData\Local\Continuum\miniconda3
```

Finding a way to fix which pip is being called should be the solution, but this is probably only a problem in my own computer. Therefore I will close the issue.
