### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by stein-e** [janclemenslab/xarray-behave#70]
For a couple of older recordings I get an AssertionError when trying to open them with xb_gui:

localhost-20191119_111912
localhost-20191119_113507
localhost-20191119_130712
localhost-20191119_131611
localhost-20191119_141535
localhost-20191119_145051
localhost-20191119_150622
localhost-20191119_152005
localhost-20191119_153924
localhost-20191129_105904
localhost-20191129_110838
localhost-20191129_112023

Traceback (most recent call last):
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/envs/xb_gui/lib/python3.7/site-packages/xarray_behave/gui/app.py", line 297, in from_dir
    include_tracks=include_tracks, include_poses=include_poses)
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/envs/xb_gui/lib/python3.7/site-packages/xarray_behave/xarray_behave.py", line 124, in assemble
    auto_event_seconds, auto_event_categories = ld.load_segmentation(filepath_segmentation)
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/envs/xb_gui/lib/python3.7/site-packages/xarray_behave/loaders.py", line 291, in load_segmentation
    segment_indices = event_utils.traces_to_eventtimes(res['segment_labels'], res['segment_names'], ['segment'])
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/envs/xb_gui/lib/python3.7/site-packages/xarray_behave/event_utils.py", line 139, in traces_to_eventtimes
    assert len(traces) == len(event_names)
AssertionError

**Comment by postpop** [comment]
That's because of some old-format deepss annotations - do you even use these? If not then we should delete the `*_song.h5` files in the res folders for these experiments.

Otherwise, I have made xb robust to these errors - this is fixed by 2916170.
