### ISSUE TITLE
still working around social vr assemble

### ISSUE THREAD

**Issue by adpala** [janclemenslab/xarray-behave#86]
Just a last update on the filepath things. It is still required to give the now '_ball' timestamps for both parameters filepath_timestamps and filepath_timestamps_ball, otherwise it crashes when interpolating balltracks.

"ValueError: zero-size array to reduction operation fmin which has no identity"

Perhaps another variable (target_samples, time, or ref_time) coming into align_time() in the line 439 of xarray_behave.py is depending on the ss object created from the filepath_timestamps, which might be wrongly configured for the new camera videos. Perhaps something in the loaders.py, in load_times() in line 232, in which we have hardcoded some things for Spinnaker or Point Grey cameras, maybe we need something in particular for Ximea.

**Comment by postpop** [comment]
damn. can you post the args you provide and the error message - I may have some time in the train to look at this.

**Comment by adpala** [comment]
Don't worry, we can work on it when you are back.

Here are the code and error.

```
import xarray_behave as xb
import numpy as np

root_flyball = 'Z:/#Data/flyball/'
datename = 'localhost-20210825_171453'
stimuli_name = 'uniform_082021'
dat_folder = 'dat'
filepath_timestamps_ball = 'Z:/#Data/flyball/dat/localhost-20210825_171453/localhost-20210825_171453_ball_timestamps.h5'
filepath_timestamps = 'Z:/#Data/flyball/dat/localhost-20210825_171453/localhost-20210825_171453_timestamps.h5'
filepath_video = 'Z:/#Data/flyball/dat/localhost-20210825_171453/localhost-20210825_171453_ball.mp4'
filepath_daq = 'Z:/#Data/flyball/dat/localhost-20210825_171453/localhost-20210825_171453_daq.h5'

ds = xb.assemble(datename, root=root_flyball, dat_path=dat_folder, res_path='res', include_balltracker=True, include_movieparams=True, resample_video_data=True, include_song=True, include_tracks=False, include_poses=False, fix_fly_indices=False, filepath_timestamps=filepath_timestamps, filepath_video=filepath_video, filepath_daq=filepath_daq, target_sampling_rate=180, filepath_timestamps_ball = filepath_timestamps_ball)
```

```
Traceback (most recent call last):
  File "z:/apalaci/code/flyball_inspection/testing_script.py", line 24, in <module>
    ds = xb.assemble(datename, root=root_flyball, dat_path=dat_folder, res_path='res', include_balltracker=True, include_movieparams=True, resample_video_data=True, include_song=True, include_tracks=False, include_poses=False, fix_fly_indices=False, filepath_timestamps=filepath_timestamps, filepath_video=filepath_video, filepath_daq=filepath_daq, target_sampling_rate=180, filepath_timestamps_ball = filepath_timestamps_ball)
  File "\\wfs-eni\ukme04\apalaci\code\tools\xarray-behave\src\xarray_behave\xarray_behave.py", line 439, in assemble
    xr_balltracks = align_time(xr_balltracks, ss_ball, target_samples, target_time=time,
  File "\\wfs-eni\ukme04\apalaci\code\tools\xarray-behave\src\xarray_behave\xarray_behave.py", line 505, in align_time
    ds = ds.interp({dim: target_frames_float}, assume_sorted=True, kwargs=interp_kwargs)
  File "C:\Users\apalaci\AppData\Local\Continuum\miniconda3\envs\xb\lib\site-packages\xarray\core\dataarray.py", line 1593, in interp
    ds = self._to_temp_dataset().interp(
  File "C:\Users\apalaci\AppData\Local\Continuum\miniconda3\envs\xb\lib\site-packages\xarray\core\dataset.py", line 2844, in interp
    variables[name] = missing.interp(var, var_indexers, method, **kwargs)
  File "C:\Users\apalaci\AppData\Local\Continuum\miniconda3\envs\xb\lib\site-packages\xarray\core\missing.py", line 630, in interp
    var, indexes_coords = _localize(var, indexes_coords)
  File "C:\Users\apalaci\AppData\Local\Continuum\miniconda3\envs\xb\lib\site-packages\xarray\core\missing.py", line 560, in _localize
    minval = np.nanmin(new_x.values)
  File "<__array_function__ internals>", line 5, in nanmin
  File "C:\Users\apalaci\AppData\Local\Continuum\miniconda3\envs\xb\lib\site-packages\numpy\lib\nanfunctions.py", line 319, in nanmin
    res = np.fmin.reduce(a, axis=axis, out=out, **kwargs)
ValueError: zero-size array to reduction operation fmin which has no identity
```

**Comment by adpala** [comment]
And this is the bit of code where I think we might be missing some special case for Ximia:

from loaders.py, line 232-241:

```
def load_times(filepath_timestamps, filepath_daq):
    """Load daq and cam time stamps, create muxer"""
    with h5py.File(filepath_timestamps, 'r') as f:
        cam_stamps = f['timeStamps'][:]

    # time stamps at idx 0 can be a little wonky - so use the information embedded in the image
    if cam_stamps.shape[1] == 2:  # time stamps from Spinnaker cam
        shutter_times = cam_stamps[:, 1]
    else:  # time stamps from point grey cam
        shutter_times = cam_stamps[:, 1] + cam_stamps[:, 2]/1_000_000  # time of "Shutter OFF"
```
