### ISSUE TITLE
With latest xb version, I cannot ds.assemble() anymore.

### ISSUE THREAD

**Issue by stein-e** [janclemenslab/xarray-behave#87]
>>> import xarray_behave as xb
>>> resname = '/home/local/UG-STUDENT/elsa.steinfath/ukme04/#Data/chainingmic/res/'
>>> datname = '/home/local/UG-STUDENT/elsa.steinfath/ukme04/#Data/chainingmic/dat/'
>>> ds = xb.assemble('localhost-20210610_091801', res_path=resname, dat_path=datname)

ERROR:root:local variable 'ss' referenced before assignment
Traceback (most recent call last):
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/lib/python3.7/site-packages/xarray_behave/xarray_behave.py", line 152, in assemble
    xr_tracks = add_time(xr_tracks, ss, dim='frame_number')
UnboundLocalError: local variable 'ss' referenced before assignment
ERROR:root:local variable 'ss' referenced before assignment
Traceback (most recent call last):
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/lib/python3.7/site-packages/xarray_behave/xarray_behave.py", line 173, in assemble
    xr_poses = add_time(xr_poses, ss, dim='frame_number')
UnboundLocalError: local variable 'ss' referenced before assignment
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/lib/python3.7/site-packages/xarray_behave/xarray_behave.py", line 320, in assemble
    first_tracked_frame = int(ss.frame(0))
UnboundLocalError: local variable 'ss' referenced before assignment

**Comment by postpop** [comment]
Data is in `dat.processed`.
