### ISSUE TITLE
Audio data not loadable for panoptikum files

### ISSUE THREAD

**Issue by stein-e** [janclemenslab/xarray-behave#91]
When running
```
resname = '.../ukme04/#Data/panoptikum/res/'
datprocname = '.../ukme04/#Data/panoptikum/dat.processed/'
ds = xb.assemble('localhost-20210622_111137', res_path=resname, dat_path=datprocname)
```
I run in the error below. This error does not occur for recent files in the /chainingmic/ folder and also not if I include `include_song=False` in the `xb.assemble()` function.

```
ERROR:root:local variable 'count' referenced before assignment
Traceback (most recent call last):
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/lib/python3.7/site-packages/xarray_behave/xarray_behave.py", line 360, in assemble
    lazy=lazy_load_song)
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/lib/python3.7/site-packages/xarray_behave/io/audio.py", line 82, in load
    non_song = f['samples'][:, non_song_channels]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/local/UG-STUDENT/elsa.steinfath/miniconda3/lib/python3.7/site-packages/h5py/_hl/selections.py", line 392, in __getitem__
    mshape = list(count)
UnboundLocalError: local variable 'count' referenced before assignment

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
/tmp/ipykernel_4184/2462129573.py in <module>
----> 1 ds = xb.assemble('localhost-20210622_111137', res_path=resname, dat_path=datprocname)#, target_sampling_rate=50,include_song=True)

~/miniconda3/lib/python3.7/site-packages/xarray_behave/xarray_behave.py in assemble(datename, root, dat_path, res_path, filepath_timestamps, filepath_video, filepath_timestamps_ball, filepath_daq, filepath_annotations, filepath_definitions, target_sampling_rate, audio_sampling_rate, audio_channels, audio_dataset, event_names, event_categories, resample_video_data, include_song, include_tracks, include_poses, include_balltracker, include_movieparams, fix_fly_indices, pixel_size_mm, lazy_load_song, make_song_events)
    366 
    367         if song_raw is None:
--> 368             song_raw = np.zeros((len(sample_times), 1), dtype=bool)
    369 
    370     # merge manual and auto events -

UnboundLocalError: local variable 'sample_times' referenced before assignment
```

**Comment by postpop** [comment]
Works for me - had to remove one of the `.` from the `...` in the paths.
